export const GET_BUSINESSES = "GET_BUSINESSES";
export const DELETE_BUSINESS = "DELETE_BUSINESS";
export const ADD_BUSINESS = "ADD_BUSINESS";
export const GET_SINGLE_BUSINESS = "GET_SINGLE_BUSINESS";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
export const FILTER_BUSINESSES = "FILTER_BUSINESSES";
